Adding support for temperature ramp and pressure in fermentation steps
MvdDonk/brewfather pull request #3
Opened 2023-07-12 10:49 UTC by stevenleadbeater

Addressing known issues resolves the closed issue #2 - I had this too and chased it down to values being set in the parts of the fermentation steps had been expected to be empty in the code. 

There's some basic test stuff in there too. Sorry about that, I didn't know how else to test the code and make sure my changes worked without isolating the failing bits and fiddling until it stopped failing. I would hope that those tests can be used by other brewers if they have a recipe that isn't compatible. Add it in as another test case and chase down anything not working. I had a quick look though, on the face of it, this minor change completes support for recipes. Can't wait to see it working in home assistant now. Thanks for writing this buddy :) feel free to message me if you want any help or are too busy for a fix!

2023-07-27 10:33 UTC, MvdDonk commented
Hi @stevenleadbeater, awsome that you created these features and fixes! 
I'm trying to test your pull request but I'm struggling with running Home Assistant. Somehow the way I ran Home Assistant previously (using DevContainer) doesn't work anymore. Everything I'm working on this addon I'm having a bad time settting up the development environment (I'm used to work in Visual Studio with C# and everything normally works out of the box ;)). Perhaps you can help me out; how did you setup your development environment?

2023-07-27 10:46 UTC, stevenleadbeater commented
@MvdDonk I used a single board computer to do it. I had an Up Board lying around that's an x86 CPU so it tends to work for everything. I didn't know there was a docker solution to doing the testing. I just deployed it to my running home assistant instance at home that does my house. 

what error are you getting when you run the docker stuff? If you drop a snippet in here I can have a look at the output and see if I can help

2023-07-27 14:44 UTC, MvdDonk requested changes
I finally got my dev environment working and tested your pull request. There way mostly one "big" issue: the setup of the integration failed because of a constructor change in Connection. 
The other things are minor, please check my comments.

2023-07-27 14:44 UTC, MvdDonk commented on dashboard.yaml
@stevenleadbeater if you can make a dashboard with only default Home Assistant entities that would be great. I can't test the current version since I don't have/use the custom types. I want the example dashboard to work on a default Home Assistant instance.

2023-07-27 14:44 UTC, MvdDonk commented on custom_components/brewfather/connection.py
> +    def __init__(self, username: str, apikey: str):
This breaks config_flow.py:
```python
connection = Connection(
            hass, data.get(CONF_USERNAME, False), data.get(CONF_PASSWORD, False)
)
``` 

If you change config_flow.py to the following it should work:
```python
        connection = Connection(
            username=data.get(CONF_USERNAME, False), 
            apikey=data.get(CONF_PASSWORD, False)
        )
```

2023-07-27 14:44 UTC, MvdDonk commented on custom_components/brewfather/test_connection.py
It sure looks your Python knowledge exceeds mine (which isn't that hard 😆). This looks like some unit test to me, can you explain how to use/run these?

2023-08-01 16:53 UTC, stevenleadbeater commented on custom_components/brewfather/connection.py
> +    def __init__(self, username: str, apikey: str):
Good spot, I'm sorry about that, I thought I'd tested that bit. Thanks for checking this over 🥰

2023-08-01 17:03 UTC, stevenleadbeater commented on dashboard.yaml
I've been thinking about this, the example dashboard is orientated around only the custom entities at the moment. The reason for this is consumer flexibility, I'm never going to have more than 4 batches going at once so I loaded up 4 sets of the custom entities but the data from which they are generated is in the `fermenting_batches` property of the sensor. So if any other person who may use this has a higher potential limit then they can copy and paste the extra sets out of the example.

I can possibly make another example dashboard for the default data? That way the component provides a starting point for either use case

2023-08-01 17:04 UTC, stevenleadbeater commented on custom_components/brewfather/test_connection.py
I've updated the README.md for command line execution instructions, I'm spoilt, my IDE just finds tests for me and I can press the play button next to them to run them 🤭

2023-08-01 17:08 UTC, stevenleadbeater commented
> I finally got my dev environment working and tested your pull request. There way mostly one "big" issue: the setup of the integration failed because of a constructor change in Connection. The other things are minor, please check my comments.

I'm sorry about this bit buddy, I should have checked the installation process over again to make sure it worked. I think I changed that bit quite late on in the development and forgot to run the configuration from zero again. Honestly python is not my first language, I can get by but I use Java and Rust more. They give me errors and refuse to run programs when I make those sorts of mistakes. I hope it didn't cause you too much trouble

2023-08-03 16:14 UTC, stevenleadbeater commented on dashboard.yaml
Ok, I moved a few things around, added another dashboard for the explicit sensors and reworked the README.md file so there are sections for the default integration or using template sensors and the multi batch dashboard. There's probably enough data coming through here now for me to hook up a chiller coil on my fermenters and run it to keep the wort at the recipe temperatures as the fermentation profiles ramp up or down using home assistant B)

2023-08-06 13:37 UTC, MvdDonk approved these changes

2023-08-06 13:39 UTC, MvdDonk commented
No problem @stevenleadbeater that's what code review is for right 😄.
Seems good now, I will merge in your PR.

2023-08-06 13:39 UTC, merged